# Generated by Django 5.1.3 on 2025-08-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projet_travaux', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='statut',
            field=models.CharField(choices=[('en_cours', 'En cours'), ('planifie', 'Planifié'), ('termine', 'Terminé'), ('suspendu', 'Suspendu')], default='en_cours', max_length=50),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='pourcentage_avancement',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
